version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend/:/app
      - /app/node_modules
    restart: on-failure
    depends_on:
      - zenbit-test-postgres
      - zenbit-test-redis
    command: >
      sh -c "npm start"
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.con
  zenbit-test-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-zenbit}'
    volumes:
      - ./zenbit-test-db:/var/lib/postgresql/zenbit
    restart: on-failure

  zenbit-test-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    restart: unless-stopped

volumes:
  zenbit-api-db: